name: Check Version Bump

on:
  pull_request:
    branches: ["master"]

jobs:
  check_version_bump:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check for version bump
        uses: bachmacintosh/need-npm-package-version-bump@v1.0.25
