name: Lint Build and Test

on:
  pull_request:
    branches: ["master"]

jobs:
  lint_build_test:
    runs-on: ubuntu-latest

    steps:
      - name: Clone project, setup Node.js and install dependencies
        uses: ./.github/actions/setup-action

      - name: Lint JavaScript
        run: npm run lint

      - name: Check formatting with Prettier
        run: npm run check-formatting

      - name: Build and E2E test App
        uses: cypress-io/github-action@v4
        with:
          browser: chrome
          build: npm run build
          start: npx serve build/
          wait-on: "http://localhost:3000"
          wait-on-timeout: 120
