name: Publish App

on:
  push:
    branches: ["master"]

jobs:
  publish_app:
    runs-on: ubuntu-latest

    steps:
      - name: Clone project, setup Node.js and install dependencies
        uses: ./.github/workflows/clone-setup-node-install-deps

      - name: Build and Publish App
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npm run deploy -- -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
