name: Publish App

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clone Project
      uses: actions/checkout@v3
      
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 16
        
    - name: Install Dependencies
      run: npm ci --ignore-scripts
      
    - name: Build and Publish App
      run: npm run deploy
