name: Publish App

on:
  push:
    branches: ["master"]

jobs:
  publish_app:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Project
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm ci --ignore-scripts

      - name: Build and Publish App
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npm run deploy -- -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
